### ISSUE TITLE
NullPointerException on terminal exit

### ISSUE THREAD

**Issue by ftc** [connectbot/connectbot#1015]
## Bug description
A NullPointerException can occur when exiting the terminal and pressing menu buttons.  This bug is caused by a non-intuitive issue where a click listener may occur after an Activity is destroyed if `finish()` is used.

## Steps to reproduce
1. In the list of hosts, select "edit host" on one of the items.
1. Turn on "close on disconnect"
1. Connect to the host and log in.
1. Run the command "sleep 1; exit" on the host
1. Quickly press the "port forwards" button from the menu in the upper right.
1. Repeat the last 2 steps until null pointer exception occurs.

The timing is kinda sensitive on this bug so doing the following increases the chances of reproducing:
1. In the device settings go to developer options and set "Don't keep activities"
2. Add `Thread.sleep(1000);` to the `closeBridge` method of `ConsoleActivity`.

## Expected behavior
The expected behavior is that the application exits the console back to the hosts list. Instead, the application closes with the following stack trace.

```
2021-09-29 11:59:27.153 12160-12160/org.connectbot.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.connectbot.debug, PID: 12160
    java.lang.NullPointerException: Attempt to read from field 'org.connectbot.service.TerminalBridge org.connectbot.TerminalView.bridge' on a null object reference
        at org.connectbot.ConsoleActivity$17.onMenuItemClick(ConsoleActivity.java:887)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
        at android.widget.AbsListView$3.run(AbsListView.java:4116)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

## Android device
I have noticed this on a few different devices but found it easiest to reproduce in the android emulator using a Pixel 3.

 - Device: Google Pixel 3 (emulated)
 - OS: Android 10 QSR1.190920.001
 - ConnectBot Version: 1.96 and version built from the main branch (e31f9ccaef955ac9f212ed25a90b2dcb25067d29)

## Server information

 - OS: OpenWrt 19.07.7
 - SSH Software and Version: dropbear v2019.78

## Additional context
I am working on a pull request to fix this problem and will submit it shortly.  I think that issue #765 may be caused by the same problem.

**Comment by ftc** [comment]
Since my fix was merged and I haven't seen the bug again, I think I am going to close this bug.  Please re-open it if you have any concerns.
