### ISSUE TITLE
Connectbot crashed while running repo sync inside screen

### ISSUE THREAD

**Issue by andronoob** [connectbot/connectbot#1036]
## Bug description

I'm using google play version of ConnectBot on LineageOS 18.1, device alioth. I was doing `repo sync` inside GNU screen on a remote VPS, following [this guide](https://wiki.lineageos.org/devices/alioth/build#download-the-source-code), then ConnectBot crashed almost every time I tried to `screen -r`.

Stacktrace:
```
java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
	at android.graphics.Bitmap.createBitmap(Bitmap.java:876)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:836)
	at org.connectbot.TerminalView.onDraw(TerminalView.java:441)
	at android.view.View.draw(View.java:22350)
	at android.view.View.buildDrawingCacheImpl(View.java:21623)
	at android.view.View.buildDrawingCache(View.java:21483)
	at android.view.View.updateDisplayListIfDirty(View.java:21203)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

## Steps to reproduce

1. Download & install ConnectBot from Play Store
2. Connect to a remote machine via SSH using ConnectBot
3. Run `repo sync` (after `repo init -u http://xxx` etc) inside `screen`
4. ConnectBot will crash in seconds

## Expected behavior

ConnectBot just runs smoothly without problem.

## Android device

 - Device: alioth
 - OS: LineageOS 18.1 based on Android 11
 - ConnectBot Version: 1.9.8

**Comment by sevenrock** [comment]
duplicate of https://github.com/connectbot/connectbot/issues/687
