### ISSUE TITLE
Crash by a NullPointerException when trying to connect sometimes

### ISSUE THREAD

**Issue by Terrible-Tornado** [connectbot/connectbot#1228]
## Bug description
When trying to connect to the host, the app sometimes crashes.
I have tried to figure out the conditions for this crash, but still not sure.

## Steps to reproduce
This could happen in many cases.

## Expected behavior
Normal connect.

## Android device
 - Device: Google Pixel 2
 - OS: Android 9.0
 - ConnectBot Version: 1.9.8-79-7b6973f

## Server information
Local of the phone.

## Logcat output
FATAL EXCEPTION: Relay
    Process: org.connectbot.debug, PID: 30109
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.connectbot.TerminalView.isShown()' on a null object reference
        at org.connectbot.service.TerminalBridge$2.beep(TerminalBridge.java:237)
        at de.mud.terminal.vt320.putChar(vt320.java:1745)
        at de.mud.terminal.vt320.putString(vt320.java:115)
        at org.connectbot.service.Relay.run(Relay.java:134)
        at java.lang.Thread.run(Thread.java:764)

**Comment by kruton** [comment]
This should be fixed with the latest conversion to Kotlin Flows. It's in v1.9.13-154 (beta) or later.
