### ISSUE TITLE
Reconnection causes crash with the setting "Close on disconnect"

### ISSUE THREAD

**Issue by Terrible-Tornado** [connectbot/connectbot#1229]
## Bug description
With the setting "Close on disconnect", reconnecting the host costs crash.

## Steps to reproduce

https://user-images.githubusercontent.com/119578731/218318404-f8da752a-7cc6-4ddf-9109-04964d0ca38b.mp4

## Expected behavior
Normal connect.

## Android device
 - Device: Google Pixel 2
 - OS: Android 9.0
 - ConnectBot Version: 1.9.8-79-7b6973f

## Server information
Guess that this may happen at any server?

## Logcat
FATAL EXCEPTION: main
    Process: org.connectbot.debug, PID: 5368
    java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setOnMenuItemClickListener(android.view.MenuItem$OnMenuItemClickListener)' on a null object reference
        at org.connectbot.ConsoleActivity.unregisterMenuListeners(ConsoleActivity.java:414)
        at org.connectbot.ConsoleActivity.closeBridge(ConsoleActivity.java:409)
        at org.connectbot.ConsoleActivity.onDisconnected(ConsoleActivity.java:217)
        at org.connectbot.service.TerminalManager.onDisconnected(TerminalManager.java:344)
        at org.connectbot.service.TerminalBridge$7.run(TerminalBridge.java:510)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by kruton** [comment]
This is fixed in the latest beta.
