### ISSUE TITLE
FATAL EXCEPTION during automate testing

### ISSUE THREAD

**Issue by WhiteSeele** [connectbot/connectbot#1401]
05-01 16:51:34.973  6736  6736 E AndroidRuntime: FATAL EXCEPTION: main
05-01 16:51:34.973  6736  6736 E AndroidRuntime: Process: org.connectbot.debug, PID: 6736
05-01 16:51:34.973  6736  6736 E AndroidRuntime: java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 2
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:76)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:87)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.widget.EditText.setSelection(EditText.java:98)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.widget.EditText.performAccessibilityActionInternal(EditText.java:138)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.view.View.performAccessibilityAction(View.java:8883)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:668)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.view.AccessibilityInteractionController.-wrap6(AccessibilityInteractionController.java)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1194)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-01 16:51:34.973  6736  6736 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

05-01 16:51:46.721  7631  7631 E AndroidRuntime: FATAL EXCEPTION: main
05-01 16:51:46.721  7631  7631 E AndroidRuntime: Process: org.connectbot.debug, PID: 7631
05-01 16:51:46.721  7631  7631 E AndroidRuntime: java.lang.IndexOutOfBoundsException: setSpan (3 ... 3) ends beyond length 2
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:76)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:87)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.widget.EditText.setSelection(EditText.java:98)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.widget.EditText.performAccessibilityActionInternal(EditText.java:138)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.view.View.performAccessibilityAction(View.java:8883)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:668)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.view.AccessibilityInteractionController.-wrap6(AccessibilityInteractionController.java)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1194)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-01 16:51:46.721  7631  7631 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by kruton** [comment]
This is obsolete because all these classes have been replaced with the Jetpack Compose.
