### ISSUE TITLE
Crash while disconnecting (unable to reproduce)

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#183]
While playing with ConnectBot trying to find a bug with ActionBar title no set properly, I came across an FC while disconnecting from the context menu in hosts list. I was connected to multiple hosts (SSH).

```
09-04 09:48:58.154  18578-18578/org.connectbot.debug E/AndroidRuntime? FATAL EXCEPTION: main
    Process: org.connectbot.debug, PID: 18578
    java.lang.IllegalStateException: Observer android.widget.AbsListView$AdapterDataSetObserver@ed0df59 was not registered.
            at android.database.Observable.unregisterObserver(Observable.java:69)
            at android.widget.BaseAdapter.unregisterDataSetObserver(BaseAdapter.java:42)
            at android.widget.ListView.setAdapter(ListView.java:470)
            at android.app.ListActivity.setListAdapter(ListActivity.java:265)
            at org.connectbot.HostListActivity.updateList(HostListActivity.java:503)
            at org.connectbot.HostListActivity.onHostStatusChanged(HostListActivity.java:508)
            at org.connectbot.service.TerminalManager.notifyHostStatusChanged(TerminalManager.java:749)
            at org.connectbot.service.TerminalManager.onDisconnected(TerminalManager.java:361)
            at org.connectbot.service.TerminalBridge$7.run(TerminalBridge.java:476)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by nindanaoto** [comment]
I guess that we can close this 10+ years old issue as an outdated one.
