### ISSUE TITLE
Issue 5.1.1 and lower

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#193]
After #192 I got a FC at startup on my Nexus 9 - 5.1.1
Everything is OK on my Nexus 5 (M)

It seems you must pass a Context to setTextAppearance() < API 23

> 640 holder.nickname.setTextAppearance(chosenStyleFirstLine);
> 641 holder.caption.setTextAppearance(chosenStyleSecondLine);

```
E/AndroidRuntime(28346): FATAL EXCEPTION: main
E/AndroidRuntime(28346): Process: org.connectbot, PID: 28346
E/AndroidRuntime(28346): java.lang.NoSuchMethodError: No virtual method setTextAppearance(I)V in class Landroid/widget/TextView; or its super classes (declaration of 'android.widget.TextView' appears in /system/framework/framework.jar)
E/AndroidRuntime(28346): 	at org.connectbot.HostListActivity$HostAdapter.getView(HostListActivity.java:640)
E/AndroidRuntime(28346): 	at android.widget.AbsListView.obtainView(AbsListView.java:2347)
E/AndroidRuntime(28346): 	at android.widget.ListView.makeAndAddView(ListView.java:1864)
E/AndroidRuntime(28346): 	at android.widget.ListView.fillDown(ListView.java:698)
E/AndroidRuntime(28346): 	at android.widget.ListView.fillFromTop(ListView.java:759)
E/AndroidRuntime(28346): 	at android.widget.ListView.layoutChildren(ListView.java:1673)
E/AndroidRuntime(28346): 	at android.widget.AbsListView.onLayout(AbsListView.java:2151)
E/AndroidRuntime(28346): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(28346): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(28346): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
E/AndroidRuntime(28346): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(28346): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(28346): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(28346): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(28346): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(28346): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(28346): 	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
E/AndroidRuntime(28346): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(28346): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(28346): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(28346): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(28346): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(28346): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(28346): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
E/AndroidRuntime(28346): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
E/AndroidRuntime(28346): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(28346): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime(28346): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(28346): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(28346): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(28346): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(28346): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(28346): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(28346): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(28346): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(28346): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28346): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28346): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(28346): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager( 1462):   Force finishing activity 1 org.connectbot/.HostListActivity
```

**Comment by kruton** [comment]
You can't directly call a method that doesn't exist because it must pass
the verifier. So since the called method didn't exist in previous (API <
23) releases, the calling method can't be verified.

You can have an "if" statement that if it passes calls another method since
the Java interpreter semantics guarantee it doesn't need to be verified
until it is called.

I'm not sure this is worth trying to fix right now.

**Comment by alescdb** [comment]
I'm not sure I understand your answer.

Both methods exist in the SDK used by ConnectBot (23), so the compiler (or preprocessor, I don't know how it is called for java) can't evaluate the statement at compilation time. So `if(API < 23)` should be evaluate at execution time and use the correct method for the user framework ?

| I'm not sure this is worth trying to fix right now.

Do you mean this should be fixed by using the deprecated API ?
