### ISSUE TITLE
Unreported/unexplained error/failure during portforward creation

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#236]
If one only enters the desired name of a new port forward (screenshot below) and presses "Create Port Forward", the port forward is not created, and the app does not inform the user that creation failed or why.

Partial stack trace:

    09-22 17:01:27.416  27549-27549/org.connectbot.debug E/CB.PortForwardListAct﹕ Could not update port forward
    java.lang.NumberFormatException: Invalid int: ""
            at java.lang.Integer.invalidInt(Integer.java:138)
            at java.lang.Integer.parseInt(Integer.java:358)
            at java.lang.Integer.parseInt(Integer.java:334)
            at org.connectbot.bean.PortForwardBean.<init>(PortForwardBean.java:72)
            at org.connectbot.PortForwardListActivity$2$2.onClick(PortForwardListActivity.java:191)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)

![portforward bug](https://cloud.githubusercontent.com/assets/1788374/10035083/37e36c80-614b-11e5-819e-d3eeb0888429.png)

**Comment by jklein24** [comment]
Looks like we need some good ol' form validation. @rhansby do you want to take this? If not, I can look into it tomorrow.

**Comment by rhansby** [comment]
@jklein24 yes I'll take it

**Comment by jklein24** [comment]
:+1:
