### ISSUE TITLE
Port forwarding doesn't work

### ISSUE THREAD

**Issue by mcdamo** [connectbot/connectbot#340]
Using ConnectBot v1.8.6 on Android 5.1.1 (Resurrection Remix) port forwards cannot be created.

Port forwards fail with log `E/CB.SSH  (20395): Could not create local port forward`

Below is anonymized adb logcat showing connection and error:

```
--------- beginning of system
I/ActivityManager(  799): START u0 {act=android.intent.action.VIEW dat=ssh://username@example.com:1234/ flg=0x4000000 cmp=org.connectbot/.ConsoleActivity} from uid 10076 on display 0
W/ContentProvider(  799): Error parsing userId.
W/ContentProvider(  799): java.lang.NumberFormatException: Invalid int: "username"
W/ContentProvider(  799):   at java.lang.Integer.invalidInt(Integer.java:138)
W/ContentProvider(  799):   at java.lang.Integer.parse(Integer.java:410)
W/ContentProvider(  799):   at java.lang.Integer.parseInt(Integer.java:367)
W/ContentProvider(  799):   at java.lang.Integer.parseInt(Integer.java:334)
W/ContentProvider(  799):   at android.content.ContentProvider.getUserIdFromAuthority(ContentProvider.java:1850)
W/ContentProvider(  799):   at android.content.ContentProvider.getUserIdFromUri(ContentProvider.java:1865)
W/ContentProvider(  799):   at com.android.server.am.ActivityManagerService$GrantUri.resolve(ActivityManagerService.java:802)
W/ContentProvider(  799):   at com.android.server.am.ActivityManagerService.checkGrantUriPermissionFromIntentLocked(ActivityManagerService.java:7483)
W/ContentProvider(  799):   at com.android.server.am.ActivityManagerService.grantUriPermissionFromIntentLocked(ActivityManagerService.java:7538)
W/ContentProvider(  799):   at com.android.server.am.ActivityStackSupervisor.startActivityUncheckedLocked(ActivityStackSupervisor.java:2236)
W/ContentProvider(  799):   at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1549)
W/ContentProvider(  799):   at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:976)
W/ContentProvider(  799):   at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3416)
W/ContentProvider(  799):   at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3403)
W/ContentProvider(  799):   at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:140)
W/ContentProvider(  799):   at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2223)
W/ContentProvider(  799):   at android.os.Binder.execTransact(Binder.java:446)
V/WindowManager(  799): addAppToken: AppWindowToken{3ad3dd92 token=Token{8f5171d ActivityRecord{2b5663f4 u0 org.connectbot/.ConsoleActivity t3958}}} to stack=1 task=3958 at 1
D/CB.ConsoleActivity(20395): onResume called
V/WindowManager(  799): Adding window Window{6ce40de u0 org.connectbot/org.connectbot.ConsoleActivity} at 15 of 24 (after Window{1ec1aacd u0 org.connectbot/org.connectbot.HostListActivity})
D/CB.ConsoleActivity(20395): We couldnt find an existing bridge with URI=ssh://username@example.com:1234/#username@example.com:1234 (nickname=username@example.com:1234), so creating one now
I/CB.TerminalBridge(20395): parentChanged() now width=135, height=82
I/ActivityManager(  799): Displayed org.connectbot/.ConsoleActivity: +146ms
I/LatinIME( 1656): Starting input. Cursor position = -1,-1
D/OpenGLRenderer(20395): endAllStagingAnimators on 0xa119a780 (ListView) with handle 0xaeea1920
I/InputAttributes( 1656): InputType.TYPE_NULL is specified
W/SubtypeLocaleUtils( 1656): KeyboardLayoutSet not found, use QWERTY: locale=en_AU extraValue=TrySuppressingImeSwitcher,AsciiCapable,SupportTouchPositionCorrection,EmojiCapable
I/Timeline(20395): Timeline: Activity_idle id: android.os.BinderProxy@2101891a time:101760173
I/CB.TerminalBridge(20395): parentChanged() now width=135, height=47
I/Timeline(  799): Timeline: Activity_windows_visible id: ActivityRecord{2b5663f4 u0 org.connectbot/.ConsoleActivity t3958} time:101760472
D/CB.SSH  (20395): Found unlocked key 'HostKey' already in-memory
D/ConnectivityService(  799): updateNetworkScore for NetworkAgentInfo [WIFI () - 177] to 60
D/ConnectivityService(  799): rematching NetworkAgentInfo [WIFI () - 177]
D/ConnectivityService(  799): Network NetworkAgentInfo [WIFI () - 177] was already satisfying request 1. No change.
D/ConnectivityService(  799): notifyType AVAILABLE for NetworkAgentInfo [WIFI () - 177]
D/ConnectivityManager.CallbackHandler( 1255): CM callback handler got msg 524290
D/ConnectivityManager.CallbackHandler(18583): CM callback handler got msg 524290
E/CB.SSH  (20395): Could not create local port forward
E/CB.SSH  (20395): Could not create local port forward
D/ConnectBot.Relay(20395): changing charset to UTF-8
D/CB.TerminalBridge(20395): OSC: 0;username@example.com: /home/username
```

**Comment by kruton** [comment]
What port number were you trying to forward?

**Comment by gerroon** [comment]
Hi
I cant get the port forwarding work either.  I can use commandline ssh like in L7171:127.0.0.1:7171 just fine. This forward can be used in any app that utilizes proxies. Dynamic socks works too in the terminal client but the same ports fail with Connectbot for me. I tried reversing remote and local thing in case I am making a mistake. That does not work either.

I tried these on Lollipop.


Thanks

**Comment by mcdamo** [comment]
Tried random high ports such as 12345, like gerroon I also confirmed that forwarding ports with ssh commandline worked.

Now I've upgraded to a new rom and ConnectBot forwarding works again, so maybe it was a bug or incompatibility with old rom.

**Comment by gerroon** [comment]
I see that Connectbot forwarding works on 5.1.1 but not on 5.0.1

**Comment by vv7v7** [comment]
If someone has problem creating a tunnel to local machine, you might like to try:
1. Create a port forwarding like: `1025` to `Local`, [ **127.0.0.1**:1025 ]
2. Create a connection to [ **localhost**:1025 ]
