### ISSUE TITLE
Support ed255519 SSH keys

### ISSUE THREAD

**Issue by dllud** [connectbot/connectbot#353]
OpenSSH 6.5 (January 2014) introduced ed25519 keys in bcrypt KDF format due to security and performance advantages. This format is now becoming widely used and is expectable to become the de-facto standard for new keys. Therefore ConnectBot should follow along and implement it.

There is already at least one pure Java implementation of ed25519, in use for i2p: [ed25519-java](https://github.com/str4d/ed25519-java).

When trying to import a ed255519 private key generated with ssh-keygen I get:

    E/CB.PubkeyListActivity( 6801): Problem parsing imported private key
    E/CB.PubkeyListActivity( 6801): java.io.IOException: Invalid PEM structure, '-----BEGIN...' missing
    E/CB.PubkeyListActivity( 6801): 	at com.trilead.ssh2.crypto.PEMDecoder.parsePEM(PEMDecoder.java:166)
    E/CB.PubkeyListActivity( 6801): 	at org.connectbot.PubkeyListActivity.readKeyFromFile(PubkeyListActivity.java:541)
    E/CB.PubkeyListActivity( 6801): 	at org.connectbot.PubkeyListActivity.access$100(PubkeyListActivity.java:81)
    E/CB.PubkeyListActivity( 6801): 	at org.connectbot.PubkeyListActivity$12.onClick(PubkeyListActivity.java:599)
    E/CB.PubkeyListActivity( 6801): 	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:941)
    E/CB.PubkeyListActivity( 6801): 	at android.widget.AdapterView.performItemClick(AdapterView.java:298)
    E/CB.PubkeyListActivity( 6801): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
    E/CB.PubkeyListActivity( 6801): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2749)
    E/CB.PubkeyListActivity( 6801): 	at android.widget.AbsListView$1.run(AbsListView.java:3423)
    E/CB.PubkeyListActivity( 6801): 	at android.os.Handler.handleCallback(Handler.java:725)
    E/CB.PubkeyListActivity( 6801): 	at android.os.Handler.dispatchMessage(Handler.java:92)
    E/CB.PubkeyListActivity( 6801): 	at android.os.Looper.loop(Looper.java:137)
    E/CB.PubkeyListActivity( 6801): 	at android.app.ActivityThread.main(ActivityThread.java:5227)
    E/CB.PubkeyListActivity( 6801): 	at java.lang.reflect.Method.invokeNative(Native Method)
    E/CB.PubkeyListActivity( 6801): 	at java.lang.reflect.Method.invoke(Method.java:511)
    E/CB.PubkeyListActivity( 6801): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
    E/CB.PubkeyListActivity( 6801): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
    E/CB.PubkeyListActivity( 6801): 	at dalvik.system.NativeStart.main(Native Method)

Despite what the exception says I've confirmed the key file has a valid PEM structure.

**Comment by kruton** [comment]
Unfortunately there is no security-audited ed25519 implementation.

**Comment by kruton** [comment]
Server keys are now supported with #370

**Comment by FabioPedretti** [comment]
OpenSSH 7.8 was just released and by default now uses the new key format. Would be nice to support it in ConnectBot, otherwise users generating key with OpenSSH 7.8 will import a non-working key (and they should convert it to the old format before importing it).

**Comment by nindanaoto** [comment]
This seems to be fixed in the main.
