### ISSUE TITLE
FC local

### ISSUE THREAD

**Issue by GesherX3** [connectbot/connectbot#504]
03-06 13:47:12.813 I/[SystemUI]RecentsView(2040): onTaskViewClicked, task key : Task.Key: 981, u: 0, lat: 1488826028453, org.connectbot, activityLabel : ConnectBot
03-06 13:47:12.833 I/[SystemUI]RecentsView(2040): Launch task: Task (981): org.connectbot [com.android.systemui.recents.model.Task@12870b70]
03-06 13:47:12.833 I/[SystemUI]RecentsView(2040):     .key: Task.Key: 981, u: 0, lat: 1488826028453, org.connectbot
03-06 13:47:12.833 D/ActivityManager(1474): setTaskToReturnTo : TaskRecord{176b4197 #981 A=org.connectbot U=0 sz=2} / mTaskToReturnTo = 1
03-06 13:47:12.833 D/ActivityManager(1474): setTaskToReturnTo : TaskRecord{176b4197 #981 A=org.connectbot U=0 sz=2} / mTaskToReturnTo = 1
03-06 13:47:12.833 D/ActivityManager(1474): setTaskToReturnTo : TaskRecord{176b4197 #981 A=org.connectbot U=0 sz=2} / mTaskToReturnTo = 1
03-06 13:47:12.863 I/SystemUI[Framework](1474): PhoneWindowManager.updateSystemUiVisibilityLw() :visibility=0x8600, pkg=org.connectbot
03-06 13:47:12.873 D/InputDispatcher(1474): Focus entered window: Window{1effe2ed u0 org.connectbot/org.connectbot.HostListActivity}
03-06 13:47:12.893 D/MediaPlayerService(1012): setDataSourceFromFD(31) -> /data/app/org.connectbot-2/base.apk
03-06 13:47:13.013 I/ActivityManager(1474): Displayed org.connectbot/.HostListActivity: +166ms
03-06 13:47:13.363 I/Timeline(1474): Timeline: Activity_windows_visible id: ActivityRecord{24fc803b u0 org.connectbot/.HostListActivity t981} time:10623599
03-06 13:47:13.693 D/InputTransport(1474): channel '1effe2ed org.connectbot/org.connectbot.HostListActivity (server)' : action=ACTION_DOWN, downTime=10623923332000, eventTime=10623923332000, pointerCount=1
03-06 13:47:13.743 D/InputTransport(1474): channel '1effe2ed org.connectbot/org.connectbot.HostListActivity (server)' : action=ACTION_UP, downTime=10623923332000, eventTime=10623970421000, pointerCount=1
03-06 13:47:13.763 I/Timeline(23467): Timeline: Activity_launch_request id:org.connectbot time:10623997
03-06 13:47:13.763 I/ActivityManager(1474): START u0 {act=android.intent.action.VIEW dat=local://null:22/ flg=0x4000000 cmp=org.connectbot/.ConsoleActivity} from uid 10098 on display 0
03-06 13:47:13.813 E/CB.ConsoleActivity(23467): java.lang.NullPointerException: Attempt to invoke interface method 'org.connectbot.bean.HostBean org.connectbot.data.HostStorage.findHost(java.util.Map)' on a null object reference
03-06 13:47:13.813 E/CB.ConsoleActivity(23467): 	at org.connectbot.transport.TransportFactory.findHost(TransportFactory.java:129)
03-06 13:47:13.813 E/CB.ConsoleActivity(23467): 	at org.connectbot.service.TerminalManager.openConnection(TerminalManager.java:279)
03-06 13:47:13.813 E/CB.ConsoleActivity(23467): 	at org.connectbot.ConsoleActivity.onNewIntent(ConsoleActivity.java:1072)
03-06 13:47:13.823 I/SystemUI[Framework](1474): PhoneWindowManager.updateSystemUiVisibilityLw() :visibility=0x8600, pkg=org.connectbot
03-06 13:47:13.823 D/InputDispatcher(1474): Focus left window: Window{1effe2ed u0 org.connectbot/org.connectbot.HostListActivity}
03-06 13:47:13.823 D/InputDispatcher(1474): Focus entered window: Window{2e00031a u0 org.connectbot/org.connectbot.ConsoleActivity}
03-06 13:47:14.243 V/NotificationService(1474): enqueueNotificationInternal: pkg=org.connectbot id=1 notification=Notification(pri=0 contentView=org.connectbot/0x1090079 vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 actions=1 vis=PRIVATE)
03-06 13:47:14.243 V/NotificationService(1474): pkg=org.connectbot canInterrupt=true intercept=false
03-06 13:47:14.243 I/NotificationServiceEx(1474): LED remove() : mLights=0|org.connectbot|1|null|10098
03-06 13:47:14.243 D/NotificationServiceEx(1474): updateLightListLocked :r=0|org.connectbot|1|null|10098, action=2
03-06 13:47:14.243 D/NotificationServiceEx(1474): notification=Notification(pri=0 contentView=org.connectbot/0x1090079 vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 actions=1 vis=PRIVATE)
03-06 13:47:14.433 I/CliptrayUtils(23467): CliptrayUtils created!! mTextView = org.connectbot.util.TerminalTextViewOverlay{3a17273b V.ED.... ......ID 0,0-0,0}
03-06 13:47:14.503 I/NotificationService(1474): enqueueToast pkg=org.connectbot callback=android.app.ITransientNotification$Stub$Proxy@2c39452c duration=0
03-06 13:47:14.623 I/ActivityManager(1474): Displayed org.connectbot/.ConsoleActivity: +832ms
03-06 13:47:14.703 I/NotificationService(1474): enqueueToast pkg=org.connectbot callback=android.app.ITransientNotification$Stub$Proxy@32255856 duration=0
03-06 13:47:14.763 E/AndroidRuntime(23467): Process: org.connectbot, PID: 23467
03-06 13:47:14.763 E/AndroidRuntime(23467): 	at org.connectbot.TerminalView$AccessibilityStateTester.doInBackground(TerminalView.java:653)
03-06 13:47:14.763 E/AndroidRuntime(23467): 	at org.connectbot.TerminalView$AccessibilityStateTester.doInBackground(TerminalView.java:609)
03-06 13:47:14.773 W/ActivityManager(1474):   Force finishing activity org.connectbot/.ConsoleActivity
03-06 13:47:14.773 D/InputDispatcher(1474): Focus left window: Window{2e00031a u0 org.connectbot/org.connectbot.ConsoleActivity}
03-06 13:47:14.833 I/NotificationService(1474): enqueueToast pkg=org.connectbot callback=android.app.ITransientNotification$Stub$Proxy@37b6a3e2 duration=0
03-06 13:47:14.913 D/SplitWindow(1474): check instance of lgWin Window{2ac37f63 u0 Application Error: org.connectbot}
03-06 13:47:14.913 D/InputDispatcher(1474): Focus entered window: Window{2ac37f63 u0 Application Error: org.connectbot}
03-06 13:47:15.283 D/InputDispatcher(1474): Window went away: Window{2e00031a u0 org.connectbot/org.connectbot.ConsoleActivity}
03-06 13:47:15.523 D/InputDispatcher(1474): Window went away: Window{1effe2ed u0 org.connectbot/org.connectbot.HostListActivity}
03-06 13:47:16.763 D/InputTransport(1474): channel '2ac37f63 Application Error: org.connectbot (server)' : action=ACTION_DOWN, downTime=10626992330000, eventTime=10626992330000, pointerCount=1
03-06 13:47:16.853 D/InputTransport(1474): channel '2ac37f63 Application Error: org.connectbot (server)' : action=ACTION_UP, downTime=10626992330000, eventTime=10627089361000, pointerCount=1
03-06 13:47:16.883 D/InputDispatcher(1474): Focus left window: Window{2ac37f63 u0 Application Error: org.connectbot}
03-06 13:47:16.883 D/InputDispatcher(1474): Window went away: Window{2ac37f63 u0 Application Error: org.connectbot}
03-06 13:47:16.923 W/ActivityManager(1474): Scheduling restart of crashed service org.connectbot/.service.TerminalManager in 1000ms
03-06 13:47:16.923 I/NotificationServiceEx(1474): LED remove() : mLights=0|org.connectbot|1|null|10098
03-06 13:47:16.923 D/NotificationServiceEx(1474): updateLightListLocked :r=0|org.connectbot|1|null|10098, action=2
03-06 13:47:16.923 D/NotificationServiceEx(1474): notification=Notification(pri=0 contentView=org.connectbot/0x1090079 vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 actions=1 vis=PRIVATE)
03-06 13:47:17.963 I/ActivityManager(1474): Start proc org.connectbot for service org.connectbot/.service.TerminalManager: pid=23632 uid=10098 gids={50098, 9997, 3003, 1028, 1015, 1023} abi=armeabi-v7a
03-06 13:47:18.023 V/NotificationService(1474): enqueueNotificationInternal: pkg=org.connectbot id=1 notification=Notification(pri=0 contentView=org.connectbot/0x1090079 vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 actions=1 vis=PRIVATE)
03-06 13:47:18.023 V/NotificationService(1474): pkg=org.connectbot canInterrupt=true intercept=false
03-06 13:47:18.023 I/NotificationServiceEx(1474): LED remove() : mLights=0|org.connectbot|1|null|10098
03-06 13:47:18.023 D/NotificationServiceEx(1474): updateLightListLocked :r=0|org.connectbot|1|null|10098, action=2
03-06 13:47:18.023 D/NotificationServiceEx(1474): notification=Notification(pri=0 contentView=org.connectbot/0x1090079 vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 actions=1 vis=PRIVATE)
03-06 13:47:18.153 D/MediaPlayerService(1012): setDataSourceFromFD(31) -> /data/app/org.connectbot-2/base.apk
03-06 13:47:18.153 W/PackageManager(2040): Failure retrieving resources for org.connectbot: Resource ID #0x0
03-06 13:47:18.293 V/JNIHelp (23632): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 242 native methods...
03-06 13:47:18.323 I/art     (23632): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.OpenSSLExtendedSessionImpl>
03-06 13:47:18.323 I/art     (23632): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.OpenSSLExtendedSessionImpl>
03-06 13:47:18.373 W/System  (23632): Could not create com.google.android.gms.org.conscrypt.OpenSSLSocketFactoryImpl with ClassLoader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.connectbot-2/base.apk"],nativeLibraryDirectories=[/data/app/org.connectbot-2/lib/arm, /vendor/lib, /system/lib]]]: com.google.android.gms.org.conscrypt.OpenSSLSocketFactoryImpl
03-06 13:47:20.753 D/NotificationService(1474): Show pkg=org.connectbot callback=android.app.ITransientNotification$Stub$Proxy@2c39452c
03-06 13:47:20.763 W/NotificationService(1474): Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@2c39452c in package org.connectbot

**Comment by nindanaoto** [comment]
There is no follow-up for this issue. I believe we can close this issue as outdated.
