### ISSUE TITLE
Crash regression on OxygenOS 5 (Android 8 fork)

### ISSUE THREAD

**Issue by ubitux** [connectbot/connectbot#650]
Since recently, I can't change the settings of a hosts anymore. Trying to change any field in the "Edit Hosts" menu leads to the following crash:

```
10-10 18:18:02.919 16911 16911 E SQLiteLog: (1) no such column: hwui
10-10 18:18:02.920 16911 16911 D AndroidRuntime: Shutting down VM
10-10 18:18:02.921 16911 16911 E AndroidRuntime: FATAL EXCEPTION: main
10-10 18:18:02.921 16911 16911 E AndroidRuntime: Process: org.connectbot, PID: 16911
10-10 18:18:02.921 16911 16911 E AndroidRuntime: android.database.sqlite.SQLiteException: no such column: hwui (code 1): , while compiling: UPDATE hosts SET hwui=? WHERE _id = ?
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1602)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1550)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at org.connectbot.HostEditorActivity$CursorPreferenceHack$Editor.commit(HostEditorActivity.java:120)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at org.connectbot.HostEditorActivity$CursorPreferenceHack$Editor.apply(HostEditorActivity.java:136)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at com.oneplus.embryo.EmbryoAppImpl.checkHWUI(:179)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.app.EmbryoApp.checkHWUI(EmbryoApp.java:107)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.view.ThreadedRenderer.<init>(ThreadedRenderer.java:368)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.view.ThreadedRenderer.create(ThreadedRenderer.java:266)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.view.ViewRootImpl.enableHardwareAcceleration(ViewRootImpl.java:994)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:707)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:330)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.preference.DialogPreference.showDialog(DialogPreference.java:319)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.preference.DialogPreference.onClick(DialogPreference.java:277)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1134)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3166)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4119)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-10 18:18:02.925 16911 16911 D OSTracker: OS Event: crash
```

Reproducible on OnePlus 3, OxygenOS 5.0.6 (Android 8.0.0).

**Comment by kruton** [comment]
I can't find that code in ConnectBot. Are you sure you're not using a fork?

**Comment by kruton** [comment]
Ah, it looks like it's a OnePlus bug. They are inserting random data into app's Preferences. You can see in the stack trace:

> 10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at org.connectbot.HostEditorActivity$CursorPreferenceHack$Editor.apply(HostEditorActivity.java:136)
10-10 18:18:02.921 16911 16911 E AndroidRuntime: 	at com.oneplus.embryo.**EmbryoAppImpl.checkHWUI**(:179)

Since we use Preference to edit the host, it ends up inserting a random column into the host update.

**Comment by nindanaoto** [comment]
This is an outdated issue for the EOL Android version.
