### ISSUE TITLE
Crash when attaching to screen

### ISSUE THREAD

**Issue by jjtt** [connectbot/connectbot#687]
## Bug description
When attaching to a screen session with "screen -r" ConnectBot crashes. Seems that this is related to something specific that is shown on the currently active screen window. Attaching from a computer and changing the active window to something else removes the issue. But ConnectBot again crashes when changing back to that specific window.

## Steps to reproduce
1. Connect to my server with my credentials with a specific window active in a screen session
2. `screen -r`
3. ConnectBot restarts back to the Hosts-list

## Expected behavior
Screen content shouldn't crash ConnectBot

## Android device
 - Device: Sony ZX2 Compact
 - OS: Android 9 52.0.A.3.126
 - ConnectBot Version: 1.9.5

## Server information
 - OS: Ubuntu Linux 16.04
 - SSH Software and Version: OpenSSH_7.2p2 Ubuntu-4ubuntu2.6, OpenSSL 1.0.2g  1 Mar 2016

### Logcat

```
01-17 08:28:47.324  8255  8914 D CB.TerminalBridge: OSC: 0;userna@serv: ~
01-17 08:28:47.325  8255  8914 D CB.TerminalBridge: Unknown character ESC[! character is 112
01-17 08:28:47.325  8255  8914 D CB.TerminalBridge: ESC [ ? 3 l, unsupported.
01-17 08:28:47.325  8255  8914 D CB.TerminalBridge: ESC [ ? 1049 h, unsupported.
01-17 08:28:47.336  8255  8255 D AndroidRuntime: Shutting down VM
01-17 08:28:47.337  8255  8255 E AndroidRuntime: FATAL EXCEPTION: main
01-17 08:28:47.337  8255  8255 E AndroidRuntime: Process: org.connectbot, PID: 8255
01-17 08:28:47.337  8255  8255 E AndroidRuntime: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:774)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at org.connectbot.TerminalView.onDraw(TerminalView.java:460)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.draw(View.java:20226)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.buildDrawingCacheImpl(View.java:19497)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.buildDrawingCache(View.java:19357)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19078)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19061)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19061)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19061)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19061)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19061)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19061)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19061)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19061)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3332)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3129)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2498)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1473)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7215)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:816)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:751)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:280)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6710)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-17 08:28:47.337  8255  8255 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-17 08:28:47.340  1386 21625 D ActivityManager: New dropbox entry: org.connectbot, data_app_crash, 4f0087ee-2f77-4eae-b1b6-22f9f370d027
01-17 08:28:47.341  1386 21625 W ActivityManager:   Force finishing activity org.connectbot/.ConsoleActivity
01-17 08:28:47.346  8255  8255 I Process : Sending signal. PID: 8255 SIG: 9
```

I have also a larger Logcat dump saved, but it will need some redacting before publication here.

### Screen session

The active screen window causing this is still open in my screen session, but will naturally vanish in the next reboot. Any hints on how to save the state? The problematic window just has a bash command line with some history visible.

**Comment by reald** [comment]
Having a similar issue here. Seems long lines in screen crashing connectbot:

**Steps to reproduce:**

1. ssh into linux box using connectbot
2. run screen, press enter
3. type in a command which is longer than the screen wide
4. connectbot is crashing one keystroke after right screen end is reached

**Reproducibility:** (almost?) always

Seems if there are too long lines screen -r triggers this bug, too.

**Comment by reald** [comment]
Seems to depend on terminal emulation type:

xterm-256color -> crash on long lines
xterm-color -> crash on long lines
xterm -> ok

**Comment by jlamoure** [comment]
Also experiencing crashing on screen reattach. Actually I started a new screen session, after some commands (and yes wrapping lines if that has something to do with it), it crashed. Then upon reattaching it would crash immediately. Switching to xterm emulation stopped crashes.

# Device:
- Moto G4 Play XT1607
- Android 7.1.2
- ConnectBot 1.9.5-oss

**Comment by gittastic** [comment]
I have same crash issue with screen.

Device: Pixel XL 2016
Android Q Beta 4 (but did same behaviour on Android 9)
ConnectBot git-v1.9.5-35-ga93051b4

**Comment by haze1434** [comment]
I experience the same issue.
ConnectBot works fine until using 'screen -r' to reattach to screen. ConnectBot then instantly crashes out, every time.

Device: Pixel 2
Android version 9
ConnectBot version is 1.9.5

**Comment by grantbow** [comment]
i stumbled on this problem today. very frustrating.

**Comment by acwest** [comment]
I have the same issue, it seems fairly recent

**Comment by thomas3120** [comment]
Same here. Only when typing commands that wrap to the next line. Quite annoying indeed, so hoping for a solution. Let me know if I can help by providing a log or something else.

**Comment by maltehi** [comment]
The same bug appears for me. When I open a screen session on a Ubuntu 18.04 (Raspi) system and type in a concatenation of commands, ConnectBot at some point just closes the connection without warning. After reopening the SSH session, ConnectBot then crashes with an error message from Android when trying to reattach the screen session. Opening a new screen session and executing the same commands on their own without concatenation works without problems.

Running ConnectBot 1.9.6 on Android 10 (Pixel 2 XL).

**Comment by majekw** [comment]
I can confirm that. It stops crashing after changing terminal type to xterm.
Android 9 (Samsung A40), ConnectBot 1.9.6.

**Comment by thomas3120** [comment]
> I can confirm that. It stops crashing after changing terminal type to xterm.
> Android 9 (Samsung A40), ConnectBot 1.9.6.

Not sure why, but that indeed did the trick for me to (Android 10, Samsung S10+, ssh server on Raspbian 10). Thank you so much for sharing this work around!

**Comment by israel-lugo** [comment]
Still happening to me in 2025 with version 1.9.12. Crash inside screen whenever I type a command that wraps around the acreen.

Can someone please look into this?

**Comment by hrimhari** [comment]
`xterm` didn't work for me, but `screen` as emulation mode did:

![Image](https://github.com/user-attachments/assets/32a4fca5-8b59-4d91-939f-b56bbef6aff5)
