### ISSUE TITLE
NPE on org.connectbot.service.TerminalBridge#onDraw

### ISSUE THREAD

**Issue by lhchavez** [connectbot/connectbot#710]
## Bug description

[`org.connectbot.service.TerminalBridge#onDraw`](https://github.com/connectbot/connectbot/blob/c4f21c10af8b0abde12ccfc3f20060362fe9e124/app/src/main/java/org/connectbot/service/TerminalBridge.java#L714) can sometimes crash with an NPE while trying to access character attributes at https://github.com/connectbot/connectbot/blob/c4f21c10af8b0abde12ccfc3f20060362fe9e124/app/src/main/java/org/connectbot/service/TerminalBridge.java#L733

This is caused by [`de.mud.terminal.VDUBuffer#insertLine(int, int, boolean)`](https://github.com/connectbot/connectbot/blob/c4f21c10af8b0abde12ccfc3f20060362fe9e124/app/src/main/java/de/mud/terminal/VDUBuffer.java#L335) not always filling up all character/attribute rows.

## Steps to reproduce

1. Connect to a Ubuntu Bionic 18.04.2 LTS host
2. Open tmux
3. Start fiddling with zoom and scroll until it crashes

## Expected behavior

It shouldn't crash

## Android device

 - Device: Android emulator (google_apis_playstore/x86)
 - OS: Android 9 PSR1.180720.075
 - ConnectBot Version: 1.9.5, as well as master.

## Server information

 - OS: Ubuntu Bionic 18.04.2 LTS
 - SSH Software and Version: OpenSSH 7.6p1
 - Tmux version: 2.6

## Additional context

One sample crash trace:

```
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: FATAL EXCEPTION: main
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: Process: org.connectbot, PID: 8683
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from null array
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at org.connectbot.service.TerminalBridge.onDraw(TerminalBridge.java:733)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at org.connectbot.TerminalView.onDraw(TerminalView.java:423)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.draw(View.java:20207)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.buildDrawingCacheImpl(View.java:19478)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.buildDrawingCache(View.java:19338)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19059)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3318)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3122)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2481)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-17 18:23:40.270 10152  8683  8683 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-17 18:23:40.276  1000  1189  3858 W ActivityManager:   Force finishing activity org.connectbot/.ConsoleActivity

**Comment by ilf** [comment]
I am also having very frequent crashes with [connectbot 1.9.5-oss](https://f-droid.org/repo/org.connectbot_10905000.apk) ([from F-Droid](https://f-droid.org/de/packages/org.connectbot/)) and tmux 2.9a.

Since there's a fix for this, it would be super helpful to have a release with this.

Thanks, and keep up the good work!
