### ISSUE TITLE
window leak in EditHostActivity

### ISSUE THREAD

**Issue by anlalalu** [connectbot/connectbot#731]
## Bug description

window leak in EditHostActivity

## Steps to reproduce

1. tap 'add host'
2. directly tap 'back'
3. dialog exists and rotate the screen
4. see error log

## Expected behavior

rotate with the dialog and with no error

## Screenshots

the dialog disappears and the error log arises

E/WindowManager: android.view.WindowLeaked: Activity org.connectbot.EditHostActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{528d2af8 V.E..... R....... 0,0-729,293} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.app.Dialog.show(Dialog.java:286)
                                                    at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:958)
                                                    at org.connectbot.EditHostActivity.showDiscardDialog(EditHostActivity.java:252)
                                                    at org.connectbot.EditHostActivity.attemptSaveAndExit(EditHostActivity.java:221)
                                                    at org.connectbot.EditHostActivity.onBackPressed(EditHostActivity.java:212)
                                                    at android.app.Activity.onKeyUp(Activity.java:2193)
                                                    at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
                                                    at android.app.Activity.dispatchKeyEvent(Activity.java:2423)
                                                    at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
                                                    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1962)
                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3845)
                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3819)
                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3551)
                                                    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3711)
                                                    at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2010)
                                                    at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1704)
                                                    at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1695)
                                                    at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1987)
                                                    at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                    at android.os.MessageQueue.nativePollOnce(Native Method)
                                                    at android.os.MessageQueue.next(MessageQueue.java:138)
                                                    at android.os.Looper.loop(Looper.java:123)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

## Android device

 - Device: android emulator
 - OS: 4.4.4
 - ConnectBot Version: [e.g., 1.9.5]

## Server information

 - OS: [e.g., Ubuntu Linux 16.10]
 - SSH Software and Version: [e.g., OpenSSH 7.1]
 - Pubkeys used (if applicable): [e.g., Ed25519]

**Comment by anlalalu** [comment]
May be solved with reference to this: https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added

Do you consider this as a defect? @kruton

**Comment by nindanaoto** [comment]
We are no longer using the reported code, so I will close this.
