### ISSUE TITLE
leaked window in HostListActivity 

### ISSUE THREAD

**Issue by anlalalu** [connectbot/connectbot#732]
## Bug description

leaked window in HostListActivity 

## Steps to reproduce

1. long click 'more options'
2. tap 'back'
3. see error

## Screenshots

stack trace:

E/WindowManager: android.view.WindowLeaked: Activity org.connectbot.HostListActivity has leaked window android.widget.LinearLayout{52919fcc V.E..... ......I. 0,0-264,96} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.support.v7.widget.TooltipPopup.show(TooltipPopup.java:84)
                                                    at android.support.v7.widget.TooltipCompatHandler.show(TooltipCompatHandler.java:168)
                                                    at android.support.v7.widget.TooltipCompatHandler.onLongClick(TooltipCompatHandler.java:116)
                                                    at android.view.View.performLongClick(View.java:4474)
                                                    at android.view.View$CheckForLongPress.run(View.java:18401)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

## Android device

 - Device: Android emulator
 - OS: 4.4.4

## Additional context

maybe can be solved like this: https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added

**Comment by nindanaoto** [comment]
We are no longer using the reported code, so I will close this.
