### ISSUE TITLE
ECDSA 521 bit keys auth always fails

### ISSUE THREAD

**Issue by msoulatre-tt** [connectbot/connectbot#76]
Trying to authenticate the client with a 521 bit sized ECDSA key signature always fails on the client side (it fails to format the signature to the ssh format, and doesn't send anything).

Here is a logcat of what happens when I try it :
```
W/System.err( 6589): java.io.IOException: Invalid signature format
W/System.err( 6589): 	at com.trilead.ssh2.signature.ECDSASHA2Verify.encodeSSHECDSASignature(ECDSASHA2Verify.java:278)
W/System.err( 6589): 	at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:272)
W/System.err( 6589): 	at com.trilead.ssh2.Connection.authenticateWithPublicKey(Connection.java:500)
W/System.err( 6589): 	at org.connectbot.transport.SSH.tryPublicKey(SSH.java:358)
W/System.err( 6589): 	at org.connectbot.transport.SSH.authenticate(SSH.java:240)
W/System.err( 6589): 	at org.connectbot.transport.SSH.connect(SSH.java:466)
W/System.err( 6589): 	at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:278)
W/System.err( 6589): 	at java.lang.Thread.run(Thread.java:838)
E/ConnectBot.SSH( 6589): Problem during handleAuthentication()
E/ConnectBot.SSH( 6589): java.io.IOException: Publickey authentication failed.
E/ConnectBot.SSH( 6589): 	at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:309)
E/ConnectBot.SSH( 6589): 	at com.trilead.ssh2.Connection.authenticateWithPublicKey(Connection.java:500)
E/ConnectBot.SSH( 6589): 	at org.connectbot.transport.SSH.tryPublicKey(SSH.java:358)
E/ConnectBot.SSH( 6589): 	at org.connectbot.transport.SSH.authenticate(SSH.java:240)
E/ConnectBot.SSH( 6589): 	at org.connectbot.transport.SSH.connect(SSH.java:466)
E/ConnectBot.SSH( 6589): 	at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:278)
E/ConnectBot.SSH( 6589): 	at java.lang.Thread.run(Thread.java:838)
E/ConnectBot.SSH( 6589): Caused by: java.io.IOException: Invalid signature format
E/ConnectBot.SSH( 6589): 	at com.trilead.ssh2.signature.ECDSASHA2Verify.encodeSSHECDSASignature(ECDSASHA2Verify.java:278)
E/ConnectBot.SSH( 6589): 	at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:272)
E/ConnectBot.SSH( 6589): 	... 6 more
```

**Comment by kruton** [comment]
Thanks for the report. Is this with the newest release?

**Comment by msoulatre-tt** [comment]
The logcat is from an older one (1.8.3) but I replicated the problem with the latest release on the play store before submitting the bug report.

**Comment by nyuszika7h** [comment]
I have the same issue too.

**Comment by msoulatre-tt** [comment]
I've had some time to look into this, it seems that Java outputs signatures with 521-bit ecdsa keys as follows:
```
30 81 -signlength- 02 .....
```

instead of what ConnectBot expects:
```
30 -signlength- 02 .....
```
(i'm not sure about the 81, it seems constant but it's only an observation)

I tried a patch that takes that into account, skipping the 81 in this case (and making the size comparison unsigned, because signlength gets >127) and it works fine, but it's pretty ugly code for now, and I'd like to understand why it's encoded like that... I couldn't find any info on this after a quick search. Any ideas ?

**Comment by kruton** [comment]
Ah, yes, that's the extended DER encoding of length in ASN.1. Since the high bit is set (0x80), the lower 7 bits are used to say how many bytes of length encoding are coming up next which is one in this case (0x01). So it should have a check for `sig[1] & 0x80 != 0` as well.

**Comment by msoulatre-tt** [comment]
That makes sense, thank you for the explanation !
I was looking for signature specific ASN.1 DER encoding, and that obviously led nowhere.

**Comment by RichJeanes** [comment]
Is there any word on this getting patched? It still seems to be present in the current version.

**Comment by yan12125** [comment]
It is still an issue? Got the same error in version 1.8.6 downloaded from Google Play.

**Comment by kruton** [comment]
Yes it will be fixed in the next release. I haven't pulled in the new
version of the SSH library.

**Comment by yan12125** [comment]
Thanks for the information. However, I got a different error with https://github.com/kruton/sshlib/commit/eb862ee8716620fa2a1c62146fc6d707600df789 and https://github.com/connectbot/connectbot/commit/5916f54d2791dcdd20f6fd017b74254f905cd5f1:
```
 26666             System.err  W  java.io.IOException: Invalid DER length
 26666             System.err  W  at com.trilead.ssh2.signature.ECDSASHA2Verify.readLength(ECDSASHA2Verify.java:282)
 26666             System.err  W  at com.trilead.ssh2.signature.ECDSASHA2Verify.encodeSSHECDSASignature(ECDSASHA2Verify.java:311)
 26666             System.err  W  at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:272)
 26666             System.err  W  at com.trilead.ssh2.Connection.authenticateWithPublicKey(Connection.java:439)
 26666             System.err  W  at org.connectbot.transport.SSH.tryPublicKey(SSH.java:360)
 26666             System.err  W  at org.connectbot.transport.SSH.tryPublicKey(SSH.java:355)
 26666             System.err  W  at org.connectbot.transport.SSH.authenticate(SSH.java:257)
 26666             System.err  W  at org.connectbot.transport.SSH.connect(SSH.java:475)
 26666             System.err  W  at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:284)
 26666             System.err  W  at java.lang.Thread.run(Thread.java:864)
 26666                 CB.SSH  E  Problem during handleAuthentication()
 26666                 CB.SSH  E  java.io.IOException: Publickey authentication failed.
 26666                 CB.SSH  E  at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:309)
 26666                 CB.SSH  E  at com.trilead.ssh2.Connection.authenticateWithPublicKey(Connection.java:439)
 26666                 CB.SSH  E  at org.connectbot.transport.SSH.tryPublicKey(SSH.java:360)
 26666                 CB.SSH  E  at org.connectbot.transport.SSH.tryPublicKey(SSH.java:355)
 26666                 CB.SSH  E  at org.connectbot.transport.SSH.authenticate(SSH.java:257)
 26666                 CB.SSH  E  at org.connectbot.transport.SSH.connect(SSH.java:475)
 26666                 CB.SSH  E  at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:284)
 26666                 CB.SSH  E  at java.lang.Thread.run(Thread.java:864)
 26666                 CB.SSH  E  Caused by: java.io.IOException: Invalid DER length
 26666                 CB.SSH  E  at com.trilead.ssh2.signature.ECDSASHA2Verify.readLength(ECDSASHA2Verify.java:282)
 26666                 CB.SSH  E  at com.trilead.ssh2.signature.ECDSASHA2Verify.encodeSSHECDSASignature(ECDSASHA2Verify.java:311)
 26666                 CB.SSH  E  at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:272)
 26666                 CB.SSH  E  ... 7 more
```

I'm using the key pair generated by ConnectBot. Please tell me if you need the key pair sample (pubkey + privkey).
