### ISSUE TITLE
ConnectBot crashes when connecting to SSH servers

### ISSUE THREAD

**Issue by luismrsilva** [connectbot/connectbot#814]
## Bug description
ConnectBot crashes when trying to connect to any of several SSH severs.
This happens using password or public-key (tested with RSA) authentication.

## Steps to reproduce
1. Open ConnectBot
2. Touch a host to start an SSH connection
3. Crash

## Expected behavior
Should see a remote shell prompt instead of crash.

## Android device
 - OS: Android 7.0
 - ConnectBot Version: 1.9.7 (beta from Play Store)

## Server information
(one of them:)
 - OS: Ubuntu Server 20.04 LTS
 - SSH Software and Version: OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
 - Pubkeys used (if applicable): Ed25519

## Additional context
Everything worked fine before the last ConnectBot update; although I'm not sure which version was installed, it was up-to date with whichever version was available before on the Play Store (beta enabled).

Here's the server log and stacktrace (from ADB) for the same connection:
- [server.log](https://github.com/connectbot/connectbot/files/4907834/server.log)
```
Jul 11 23:13:05 ubuntu sshd[3520]: message repeated 8 times: [ debug1: server_input_global_request: rtype keepalive@openssh.com want_reply 1]
Jul 11 23:13:06 ubuntu sshd[3419]: debug1: Forked child 3530.
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: Set /proc/self/oom_score_adj to 0
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: inetd sockets after dupping: 4, 4
Jul 11 23:13:06 ubuntu sshd[3530]: Connection from 10.0.1.11 port 42893 on 10.0.0.123 port 22 rdomain ""
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: Remote protocol version 2.0, remote software version TrileadSSH2Java_213
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: no match: TrileadSSH2Java_213
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: permanently_set_uid: 111/65534 [preauth]
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: SSH2_MSG_KEXINIT received [preauth]
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: kex: algorithm: curve25519-sha256 [preauth]
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: kex: host key algorithm: ssh-ed25519 [preauth]
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none [preauth]
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none [preauth]
Jul 11 23:13:06 ubuntu sshd[3530]: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
```

- [stacktrace.txt](https://github.com/connectbot/connectbot/files/4907833/stacktrace.txt)
```
07-12 00:13:06.185 15275 15321 E AndroidRuntime: FATAL EXCEPTION: Thread-4
07-12 00:13:06.185 15275 15321 E AndroidRuntime: Process: org.connectbot, PID: 15275
07-12 00:13:06.185 15275 15321 E AndroidRuntime: java.lang.IllegalStateException: Arithmetic error in curve multiplication with the public key: 0900000000000000000000000000000000000000000000000000000000000000
07-12 00:13:06.185 15275 15321 E AndroidRuntime: 	at com.google.crypto.tink.subtle.Curve25519.curveMult(Curve25519.java:332)
07-12 00:13:06.185 15275 15321 E AndroidRuntime: 	at com.google.crypto.tink.subtle.X25519.computeSharedSecret(X25519.java:103)
07-12 00:13:06.185 15275 15321 E AndroidRuntime: 	at com.google.crypto.tink.subtle.X25519.publicFromPrivate(X25519.java:121)
07-12 00:13:06.185 15275 15321 E AndroidRuntime: 	at com.trilead.ssh2.crypto.dh.Curve25519Exchange.init(Curve25519Exchange.java:43)
07-12 00:13:06.185 15275 15321 E AndroidRuntime: 	at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:574)
07-12 00:13:06.185 15275 15321 E AndroidRuntime: 	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:614)
07-12 00:13:06.185 15275 15321 E AndroidRuntime: 	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:310)
07-12 00:13:06.185 15275 15321 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

Regarding the "public key" seen on the stacktrace (`0900000000000000000000000000000000000000000000000000000000000000`):
I've seen stacktraces with different, maybe random, values there before. But now every host I test crashes with that value there, everytime.

**Comment by kruton** [comment]
This looks like a critical randomness failure. I'll investigate what could be going wrong.

**Comment by thaidn** [comment]
Thanks for the report. This looks like a bug in Tink. I'll investigate.

**Comment by thaidn** [comment]
Can you share the private key that caused the issue?

**Comment by luismrsilva** [comment]
@thaidn thank you for your reply.
Just to be clear, do you mean the value of `privateKey` [here](https://github.com/google/tink/blob/a8ec74d083068cd5e1ebed86fd8254630617b592/java_src/src/main/java/com/google/crypto/tink/subtle/X25519.java#L121)?
(this link is for Tink `1.4.0`, whereas `1.4.0-rc2`is being used)

**Comment by thaidn** [comment]
Yes, if it is not inconvenient for you to do so.

**Comment by luismrsilva** [comment]
I've managed to reproduce the crash with the debug variant of ConnectBot using the `debugImplementation` of sshlib 2.2.14 and tink 1.4.0-rc2. I set a breakpoint on the [line](https://github.com/google/tink/blob/a8ec74d083068cd5e1ebed86fd8254630617b592/java_src/src/main/java/com/google/crypto/tink/subtle/Curve25519.java#L330) where the IllegalStateException is thrown to read the variables from memory for 3 separate instances of the crash. These include the variables for each scope leading to the private key.
Here are the privateKey values and other variables:

- privateKey = `{119, 127, 11, -105, -122, -51, -112, 119, -27, 112, -79, 72, -59, 105, 100, 111, 119, -18, 81, -76, 104, -81, 55, 8, 42, -77, -1, 39, 64, 124, 83, -69}`; from [variables_crash1.txt](https://github.com/connectbot/connectbot/files/4997058/variables_crash1.txt)

-  privateKey = `{-73, 17, 51, 40, 0, 92, 31, 85, -16, 53, 86, 8, -64, 99, 63, -72, 38, -123, 37, -25, -54, -97, -126, 104, 11, -94, -56, -119, 14, -45, 62, -111}`; from [variables_crash2.txt](https://github.com/connectbot/connectbot/files/4997059/variables_crash2.txt)

-  privateKey = `{127, -83, -16, 85, -38, 15, 97, -44, -19, 80, 109, 68, 2, 100, 103, -71, -41, 87, 115, 10, -27, -58, -86, -39, -52, 31, -1, 32, -72, 46, 86, -115}`; from  [variables_crash3.txt](https://github.com/connectbot/connectbot/files/4997060/variables_crash3.txt)

Please let me know if you need more info or if there is a better way to present these.

**Comment by kruton** [comment]
Thanks for the excellent investigative work, @luismrsilva. That will help a lot.

**Comment by thaidn** [comment]
Unfortunately it looks like we couldn't reproduce. `com.google.crypto.tink.subtle.X25519.publicFromPrivate` doesn't crash with any of the provided private keys.

@kste had a closer look at this, and reported that:

>  I tried ~2^30 random scalars multiplied by the base point, but did not get any error in the collinearity check.
> Using the debug output provided on Github, I could reproduce that the values dumped cause the collinearity check to fail.
> Using the private keys provided on Github, I could not reproduce that if you multiple those by the base point it will lead to the observed error.

> Especially the last point makes it difficult to progress further, as I'm not sure if it's platform specific issue happening and can't get to the same state with the given private key. From Tink 1.4.0-rc2 to the current head there haven't been any changes to the field arithmetic, so it seems unlikely that the bug would not be present in the current head.

@luismrsilva would you mind sharing the code that produced the crashes?

**Comment by thaidn** [comment]
@luismrsilva please also report the platform on which you reproduced this issue. Maybe this is platform-specific.

**Comment by luismrsilva** [comment]
Thank you for your replies and for looking into this.

For the crashes above I had the code as such:
- Checkout commit `b933dc10d5030712bdfdf87fdbffaa873accd66b` (tag: `v1.9.7`, tag: `git-v1.9.7`);
- Apply [this patch](https://github.com/connectbot/connectbot/files/5005640/patch_over_v1.9.7.txt) to change the relevant dependencies to `debugImplementation`.

It crashes on a phone with Android 7.0 (NRD90M).
Unfortunately, I could **not** reproduce it on other devices. Tested:
- Device with Android 6.0.1;
- Device with Android 8.1.0;
- Emulator with Android 7.0 x86 (x);
- Emulator with Android 7.0 arm64-v8a (same arch as the phone where the crash happens);

Therefore I'd say it's platform-specific.

-----
I did some more digging, having hardcoded the `privateKey` from crash1 above ([another patch](https://github.com/connectbot/connectbot/files/5009952/digging_patch_over_v1.9.7.txt) over `v1.9.7`), calling `X25519.publicFromPrivate(privateKey)` on `HostListActivity.onResume()` so I don't have to keep choosing a host (I tired using an androidTest for that, but I get an error about sharedId when trying to install it on the phone).

I've narrowed down the issue to the execution of the following function, on line 294, when ` i == 3 && j == 7`:
[monty(nqx2, nqz2, nqpqx2, nqpqz2, nqx, nqz, nqpqx, nqpqz, q);](https://github.com/google/tink/blob/a8ec74d083068cd5e1ebed86fd8254630617b592/java_src/src/main/java/com/google/crypto/tink/subtle/Curve25519.java#L294)

I say this because if I set two [conditional breakpoints](https://user-images.githubusercontent.com/6828187/89096261-46ee4c00-d3cd-11ea-96ad-3dac5a59b947.png), one on line 294 and the other on line 295, with `i >= 3 && j == 7`, I see that before the function executes the variables in scope are the same compared to an instance on Emulator (x) and a crashing instance; **after that function executes, variables differ between the instances**.
Data on the breakpoints (data is from before that line executes):
| Line | Emulator (ok) | Device (crash) | Variables |
|------|---------------|--------|---------|
| 294  | [294_emu_ok.txt](https://github.com/connectbot/connectbot/files/5009939/294_emu_ok.txt) | [294_dev_ok.txt](https://github.com/connectbot/connectbot/files/5009940/294_dev_ok.txt)  | Equal |
| 295  | [295_emu_ok.txt](https://github.com/connectbot/connectbot/files/5009943/295_emu_ok.txt) | [295_dev_bad.txt](https://github.com/connectbot/connectbot/files/5009944/295_dev_bad.txt)  | **Differ** |

However, if I step into the function and run each line one by one, comparing variables every time, I find no differences. Maybe this is timing-sensitive? Maybe I messed up somewhere.

Anyway, the problem definitely happens inside [this for](https://github.com/google/tink/blob/a8ec74d083068cd5e1ebed86fd8254630617b592/java_src/src/main/java/com/google/crypto/tink/subtle/Curve25519.java#L287), not before it.

**Comment by kruton** [comment]
If you step line-by-line it goes into interpreter mode and doesn't run the precompiled code. It would be useful to have the files from `/data/dalvik-cache/` for Connectbot to see what it's compiling into.

I suspect that you're right this is a device-specific issue and it has a modified runtime compiler.

**Comment by luismrsilva** [comment]
Thank you for your reply.

Do you have any suggestion on how I could get the dalvik-cache files? I've manage to cd into `/data/dalvik-cache/arm64/` in adb shell on the phone, but it has no permission to list files there and I don't have root.

I listed the files in the emulator (as root), which in this case are in `/data/dalvik-cache/x86/`, hoping to figure the path for the files, but there's no mention of ConnectBot or any of the relevant libraries. There are only `.art` and `.oat` files starting with `system@framework@boot`.

**Comment by kruton** [comment]
If you installed a debug version of Connectbot, you can use `run-as` in the `adb shell` which should give you access to whatever the application can see including `.oat` files. I'm not sure about the file layout in Nougat. I'll try to check with an emulator later and update here where an app's compiled `.dex` files should be.

**Comment by kruton** [comment]
The `.oat` files should be in `/data/app/[org.connectbot something]/oat/[processor]/...` but it might be easier to manually acquire the `.oat` file:

1. `curl https://github.com/connectbot/connectbot/releases/download/git-v1.9.7/ConnectBot-git-v1.9.7-google.apk -o connectbot.apk -SL`
1. `adb push connectbot.apk /data/local/tmp`
1. `adb shell dex2oat --dex-file=/data/local/tmp/connectbot.apk --oat-file=/data/local/tmp/connectbot.oat`
1. `adb shell oatdump --oat-file=/data/local/tmp/connectbot.oat > connectbot-oatdump.txt`
1. `gzip connectbot-oatdump.txt`

Then upload that `connectbot-oatdump.txt.gz` to the issue.

**Comment by luismrsilva** [comment]
Thank you for your replies.

I've run the provided commands.
Here is the bzip2-compressed output (9.2 MiB), compressed as zip so GitHub would let me upload it: [connectbot-oatdump.txt.bz2.zip](https://github.com/connectbot/connectbot/files/5025983/connectbot-oatdump.txt.bz2.zip)

I could not find `.oat` files for the debug version (using `run-as org.connectbot.debug`) on the phone:
- `ls` in `/data/data/org.connectbot.debug/` shows `cache/`, `code_cache/`, `databases/`, `lldb/`, `shared_prefs/`.
- `cache/` and `code_cache/` are empty.
- `/data/app/org.connectbot.debug/` does not exist.

`/data/app/org.connectbot/` does not exist either.
`/data/app/` does exist.

**Comment by luismrsilva** [comment]
This also affects [bVNC Free (com.iiordanov.freebVNC v5.0.1)](https://github.com/iiordanov/remote-desktop-clients) on the same phone, which crashes with the same exception, same stack trace, except it shows random public keys instead of always showing `0900000000000000000000000000000000000000000000000000000000000000` (tested some 5 times).

**Comment by luismrsilva** [comment]
I've built ConnectBot `v1.9.6` and it works fine on the phone.
I though it might be using a different `tink` version and wanted to compare these, but it appears that **`v1.9.6` does not use `tink` at all**.

This table shows which versions are used with links to where the library is listed as a dependency and finally imported.
| ConnectBot | sshlib | tink      | (import) |
|------------|--------|-----------|--------|
| v1.9.6     | [2.2.9](https://github.com/connectbot/connectbot/blob/v1.9.6/app/build.gradle#L250)  | -         | [djb.Curve25519](https://github.com/connectbot/sshlib/blob/2.2.9/sshlib/src/main/java/com/trilead/ssh2/crypto/dh/Curve25519Exchange.java#L3) |
| v1.9.7     | [2.2.14](https://github.com/connectbot/connectbot/blob/v1.9.7/app/build.gradle#L253) | [1.4.0-rc2](https://github.com/connectbot/sshlib/blob/2.2.14/build.gradle.kts#L38) | [com.google.crypto.tink.subtle.X25519](https://github.com/connectbot/sshlib/blob/2.2.14/src/main/java/com/trilead/ssh2/crypto/dh/Curve25519Exchange.java#L3)  |

**Comment by thaidn** [comment]
@luismrsilva I'd advise against using djb.Curve25519 until we know for sure what happened.

The failure in Tink could be working as intended. Tink has a novel defense against fault attacks including faulty hardware. It throws the exception reported here when it encounters an unexpected computation result. If you accepted the result, at best it wouldn't work at all (i.e., because it'd different from the result on the server side), at worst you'd leak the private key.

**Comment by kruton** [comment]
Oh, `djb.Curve25519` in 2.2.9 was replaced with Tink in 2.2.15 which coincided with this error. The other side is most likely OpenSSH, so nobody is using `djb.Curve25519` in this exchange.

My original aim was to get rid of `djb.Curve25519` with the switch to Tink, of course.

**Comment by thaidn** [comment]
Thanks @kruton.

Just an update: I've bought an ASUS phone running MediaTek and will have it in a week. Will update once I've got more information.

**Comment by user8446** [comment]
Hi,

Adding that I have an ASUS tablet on Android 7 that also does not work, but works on my Moto G7 running Android 10. Using keys. Similar as above:

SSH log shows:
9944 2022-02-07 10:49:03.342 Connection closed by x.x.x.x port 46845 [preauth]

The app shows:
Source file:
Curve25519.java

Source class:
com.google.crypto.tink.subtle.Curve25519

Source method:
curveMult

Line number:
332

Stack trace:
java.lang.IllegalStateException: Arithmetic error in curve multiplication with the public key: xxxxxx
at com.google.crypto.tink.subtle.Curve25519.curveMult(Curve25519.java:332)
at com.google.crypto.tink.subtle.X25519.computeSharedSecret(X25519.java:103)

at com.trilead.ssh2.crypto.dh.Curve25519Exchange.setF(Curve25519Exchange.java:67)
at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:703)
at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:614)
at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:310)
at java.lang.Thread.run(Thread.java:761)

**Comment by s09bQ5** [comment]
https://github.com/connectbot/connectbot/commit/f9f0590b68cc5779c0bd4685fc6ae36d70d462e1 talks about fixing a bug that sounds a lot like this one. Is it really fixed? I'm having the same problem with F-Droid's ConnectBot 1.9.8 build on an Archos Oxygen 70 (MTK 8163A, rev 2 shipped with Android 7).

**Comment by user8446** [comment]
The bug is there for me w/ the v1.9.8 F-Droid release. I even tried a newer [release](https://github.com/connectbot/connectbot/releases) approx 2 months ago but it appears that they are just auto-builds with updated libraries.

**Comment by s09bQ5** [comment]
1.9.10 still crashes on my Archos Oxygen 70.
